FROM python:3.6
COPY ./app /app
WORKDIR /app

RUN cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime
RUN echo Asia/Taipei > /etc/timezone

RUN pip install -r requirements.txt

ENTRYPOINT ["python","main.py"]


